This file is generated by go-licenses v2.0.1 using
packaging/debian/copyright.tpl. Do not edit it directly; run "make notices".

Upstream-Name: tmus
Upstream-Source: https://github.com/bpicode/tmus

===============================================================================
tmus
===============================================================================

Files: *
Copyright: 2026 bpicode
License: GPL-3.0-only
 The complete GNU General Public License version 3 is available in
 /usr/share/common-licenses/GPL-3 on Debian systems and in the top-level
 LICENSE file distributed with tmus.

===============================================================================
Incorporated material: Catppuccin Palette
===============================================================================

Files: internal/ui/theme/preset.go
Component: Catppuccin Palette
Version: v1.8.0
Revision: 07d02aa110ef9eb7e7427afca5c73ba9cf7f8ebd
Source: https://github.com/catppuccin/palette/tree/v1.8.0
Copyright: Copyright (c) 2021 Catppuccin
License: MIT

MIT License

Copyright (c) 2021 Catppuccin

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

===============================================================================
Incorporated material: Primer Primitives
===============================================================================

Files: internal/ui/theme/preset.go
Component: Primer Primitives
Version: v11.10.0
Revision: 3f51f80ee9510974032917c9b8ac9586656c88bc
Source: https://github.com/primer/primitives/tree/v11.10.0
Copyright: Copyright (c) 2018 GitHub Inc.
License: MIT

The MIT License (MIT)

Copyright (c) 2018 GitHub Inc.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

===============================================================================
Incorporated material: Waves
===============================================================================

Files: internal/app/player/m4a.go internal/app/player/ogg.go
Component: Waves
Version: v0.1.42
Revision: 3052206722f6b50eed6cd2b783b210e48db1ba03
Source: https://github.com/llehouerou/waves/tree/v0.1.42
Copyright: Waves contributors; no explicit notice was present upstream.
License: GPL-3.0-only
 The complete GNU General Public License version 3 is available in
 /usr/share/common-licenses/GPL-3 on Debian systems and in the top-level
 LICENSE file distributed with tmus.

===============================================================================
Go standard library and runtime
===============================================================================

Component: Go standard library and runtime
Version: Go 1.26 series
Source: https://go.googlesource.com/go/+/refs/heads/release-branch.go1.26
Copyright: Copyright 2009 The Go Authors. All rights reserved.
License: BSD-3-Clause

Copyright 2009 The Go Authors.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

   * Redistributions of source code must retain the above copyright
notice, this list of conditions and the following disclaimer.
   * Redistributions in binary form must reproduce the above
copyright notice, this list of conditions and the following disclaimer
in the documentation and/or other materials provided with the
distribution.
   * Neither the name of Google LLC nor the names of its
contributors may be used to endorse or promote products derived from
this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

===============================================================================
Compiled Go components
===============================================================================
{{ range . }}
{{ if eq .Name "github.com/llehouerou/go-m4a" -}}
-------------------------------------------------------------------------------
Component: {{ .Name }}
Version: {{ .Version }}
Source: https://github.com/llehouerou/go-m4a/tree/{{ .Version }}
Copyright: No copyright notice was found in the v0.1.0 source.
License: UNKNOWN
Comment: The upstream v0.1.0 source contains no license declaration. This
 component is intentionally recorded as UNKNOWN; no license terms are inferred.

{{ else -}}
-------------------------------------------------------------------------------
Component: {{ .Name }}
Version: {{ .Version }}
Versioned-Source-License-URL: {{ .LicenseURL }}
Copyright: Copyright notices are reproduced in the license text below when
 present upstream.
License: {{ .LicenseName }}

{{ .LicenseText }}

{{ end -}}
{{ end -}}
