name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Fail if no tag
        if: ${{ github.ref_type != 'tag' }}
        run: exit 1
      - name: Import GPG key
        run: |
          echo "${{ secrets.MAINTAINER_PUBLIC_KEY }}" | gpg --import
      - name: Verify tag signature
        run: |
          git verify-tag ${{ github.ref_name }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev
      - name: Go toolchain
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
